apiVersion: sources.knative.dev/v1alpha1
kind: RedisStreamSource
metadata:
  name: mystream
  namespace: knative-serving
spec:
  address: "rediss://user:userpassword@asdf1234.databases.appdomain.cloud:30285"
  # address: "rediss://redis.redis.svc.cluster.local:6379"
  stream: mystream
  group: mygroup
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: async-consumer